version: 2

models:
  - name: answers
    description: "Answers dimention table"
  - name: questions
    description: "Info and metrics about questions"

  - name: tags
    description: "Tag dimention table"

  - name: users
    description: "User Info"